# Generated by Django 4.1.2 on 2022-10-20 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MOUS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="MOUS ID값"
                    ),
                ),
                ("sn", models.CharField(max_length=20, verbose_name="군번")),
                ("rk", models.CharField(max_length=20, verbose_name="계급")),
                ("nm", models.CharField(max_length=20, verbose_name="이름")),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="영상 ID값"
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="파일명")),
                (
                    "file",
                    models.FileField(null=True, upload_to="", verbose_name="영상파일"),
                ),
                ("owner", models.CharField(max_length=20, verbose_name="소유자 군번")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추가된 날짜"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(auto_now=True, verbose_name="업뎃 된 날짜"),
                ),
                ("unit", models.CharField(max_length=255, verbose_name="녹화된 부대")),
            ],
        ),
        migrations.CreateModel(
            name="ViewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="조회기록 ID값"
                    ),
                ),
                ("viewer", models.CharField(max_length=20, verbose_name="조회자 군번")),
                (
                    "ip_address",
                    models.CharField(max_length=255, verbose_name="조회한 IP주소"),
                ),
                (
                    "record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.record",
                        verbose_name="녹화영상 ID값",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="조회권한 ID값"
                    ),
                ),
                (
                    "allowed_user",
                    models.CharField(max_length=20, verbose_name="권한부여받은 유저 군번"),
                ),
                (
                    "record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.record",
                        verbose_name="녹화영상 ID값",
                    ),
                ),
            ],
        ),
    ]
