# Generated by Django 4.1.2 on 2022-10-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="mous",
            table="MOUS",
        ),
    ]
