# Generated by Django 4.1.2 on 2022-10-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_mous_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="mous",
            table=None,
        ),
    ]
