# Generated by Django 4.1.2 on 2022-10-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mous_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='관리자 ID값')),
                ('sn', models.CharField(max_length=20, verbose_name='군번')),
                ('unit', models.CharField(max_length=20, null=True, verbose_name='관리부대 코드')),
                ('type', models.CharField(choices=[('MASTER', '최고관리자'), ('ADMIN', '관리자')], max_length=10, verbose_name='괸리자유형')),
            ],
        ),
    ]
