# Generated by Django 4.1.2 on 2022-10-27 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewhistory',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mous', verbose_name='조회자'),
        ),
    ]
