# Generated by Django 4.1.2 on 2022-10-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_viewhistory_viewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='부대 ID값')),
                ('name', models.CharField(max_length=20, verbose_name='부대명')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_unit', to='api.org', verbose_name='관리부대')),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.org', verbose_name='관리부대'),
        ),
    ]
