# Generated by Django 4.1.2 on 2022-10-27 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_org_alter_admin_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_unit', to='api.org', verbose_name='관리부대'),
        ),
    ]
