# Generated by Django 4.1.2 on 2022-10-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_admin_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='sn',
            field=models.CharField(max_length=20, verbose_name='군번'),
        ),
    ]
