# Generated by Django 4.1.2 on 2022-10-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_admin_sn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Org',
            new_name='Unit',
        ),
    ]
