# Generated by Django 4.1.2 on 2022-10-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_org_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='unit',
        ),
    ]
