# Generated by Django 4.1.2 on 2022-10-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_admin_sn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='sn',
            new_name='user',
        ),
    ]
