# Generated by Django 4.1.2 on 2022-10-28 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_sn_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='allowed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mous', verbose_name='권한부여받은 유저 군'),
        ),
    ]
