# Generated by Django 4.1.2 on 2022-10-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_record_id_permission_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewhistory',
            old_name='record_id',
            new_name='record',
        ),
    ]
