# Generated by Django 4.1.2 on 2022-10-29 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_record_id_viewhistory_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.org', verbose_name='녹화된 부대'),
        ),
    ]
