# Generated by Django 4.1.2 on 2022-10-29 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_record_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='approval_status',
            field=models.CharField(choices=[('NOTHING', '반출신청안함'), ('PENDING', '승인요청중'), ('APPROVED', '승인됨'), ('REJECTED', '거절됨')], default=None, max_length=10, null=True, verbose_name='반출 승인 상태'),
        ),
        migrations.AddField(
            model_name='record',
            name='approver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mous', verbose_name='반출 승인 처리자'),
        ),
        migrations.AlterField(
            model_name='record',
            name='approved_at',
            field=models.DateTimeField(null=True, verbose_name='반출 승인 날짜'),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='조회권한 ID값')),
                ('allowed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mous', verbose_name='권한부여받은 유저 군')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.record', verbose_name='녹화영상 ID값')),
            ],
        ),
    ]
