# Generated by Django 4.1.2 on 2022-10-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_record_approval_comment_record_reject_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='request_at',
            field=models.DateTimeField(null=True, verbose_name='반출 요청 날짜'),
        ),
    ]
