# Generated by Django 4.1.2 on 2022-10-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_record_request_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='approval_status',
            field=models.CharField(choices=[('NOTHING', '반출신청안함'), ('PENDING', '승인요청중'), ('APPROVED', '승인됨'), ('REJECTED', '거절됨')], default='NOTHING', max_length=10, verbose_name='반출 승인 상태'),
        ),
    ]
